### PR TITLE
Update test matrix and fix tests

### PR DESCRIPTION
**Pull request by kratman**
Updating the tests to cover python 3.10-3.12

### CODE REVIEW

**Comment by kratman** [comment]
@valentinsulzer This should make the this library work with python 3.10 and above. After this review can you make the new release?

**Comment by kratman** [comment]
I already updated the version number in this PR as well

**Review by valentinsulzer — APPROVED** [review]

**Comment by valentinsulzer** [comment]
Released!

**Comment by kratman** [comment]
Thanks. I made the GitHub release tag to match

**Pull request merged**
